# Generated by Django 2.0.7 on 2018-07-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='additional_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='blogs_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='extractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=250)),
                ('extractor_name', models.CharField(max_length=100)),
                ('no_of_pages', models.IntegerField(default=0)),
                ('no_of_blogs', models.IntegerField(default=0)),
                ('start_page', models.IntegerField(default=0)),
                ('days_to_extract', models.IntegerField(default=0)),
                ('days_to_negate', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duplicate_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='extractor_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_style', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(max_length=200)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('function_name', models.CharField(max_length=20)),
                ('extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.extractor')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post_time', models.TimeField()),
                ('file_path', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.author')),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.additional_information')),
            ],
        ),
        migrations.CreateModel(
            name='post_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='refresh_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='run_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('run_status', models.CharField(max_length=20)),
                ('extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.extractor')),
            ],
        ),
        migrations.CreateModel(
            name='run_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_pages', models.IntegerField()),
                ('no_of_blogs', models.IntegerField()),
                ('start_page', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_to_extract', models.IntegerField()),
                ('days_to_negate', models.IntegerField()),
                ('extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.extractor')),
            ],
        ),
        migrations.CreateModel(
            name='same_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('old_author', models.CharField(max_length=100)),
                ('new_author', models.CharField(max_length=30)),
                ('old_post_id', models.CharField(max_length=30)),
                ('new_post_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='run_info',
            name='run_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.run_version'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post_content'),
        ),
        migrations.AddField(
            model_name='log',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.run_info'),
        ),
        migrations.AddField(
            model_name='log',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.severity'),
        ),
        migrations.AddField(
            model_name='extractor',
            name='extractor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.extractor_type'),
        ),
        migrations.CreateModel(
            name='mypost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('blogs.post',),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'title')},
        ),
    ]
