# Generated by Django 2.0.7 on 2018-07-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='extractor',
            new_name='extr',
        ),
    ]
