# Generated by Django 2.0.7 on 2018-07-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180728_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='extr',
            new_name='extractor',
        ),
    ]
