# Generated by Django 2.0.7 on 2018-07-30 05:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180728_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attrs', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
