# Generated by Django 2.0.7 on 2018-07-30 06:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_shopitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='json_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datas', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
