# Generated by Django 2.0.7 on 2018-07-30 06:55

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180730_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json_post',
            name='datas',
            field=django_mysql.models.JSONField(default=dict, unique=True),
        ),
    ]
